CFLAGS = -g -Wall -Wno-unused-parameter
CC = gcc

PROGRAMS = mainLC

.PHONY: all clean

all: $(PROGRAMS)

mainLC: mainLC.o biblioLC.o entreeSortieLC.o utils.o benchmarking.o
	$(CC) $(CFLAGS) -o $@ $^

mainLC.o: mainLC.c
	$(CC) $(CFLAGS) -c $<

biblioLC.o: biblioLC.c
	$(CC) $(CFLAGS) -c $<

entreeSortieLC.o: entreeSortieLC.c
	$(CC) $(CFLAGS) -c $<

utils.o: utils.c
	$(CC) $(CFLAGS) -c $<

benchmarking.o: benchmarking.c
	$(CC) $(CFLAGS) -c $<


clean:
	rm -f *.o *.gch *~ $(PROGRAMS)