CFLAGS = -g -Wall -Wno-unused-parameter
CC = gcc

ifdef BENCHMARKING
    CFLAGS += -DBENCHMARKING
endif

PROGRAMS = mainH

.PHONY: all clean

all: $(PROGRAMS)

mainH: mainH.o biblioH.o entreeSortieH.o utils.o
	$(CC) $(CFLAGS) -o $@ $^ -lm

mainH.o: mainH.c
	$(CC) $(CFLAGS) -c $<

biblioH.o: biblioH.c
	$(CC) $(CFLAGS) -c $<

entreeSortieH.o: entreeSortieH.c
	$(CC) $(CFLAGS) -c $<

utils.o: utils.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o *.gch *~ $(PROGRAMS) ./rechercheMultiplesH.txt